services:
  paymentsapi:
    image: paymentsapi
    container_name: payments-api

    build:
      context: .
      dockerfile: src/PaymentsAPI/Dockerfile

    ports:
      - "8082:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"

      ConnectionStrings__WebApiDatabase: "Server=payments-sqlserver,1433;Database=FCGPayments;User Id=sa;Password=SuaSenhaForte@123;TrustServerCertificate=True;Encrypt=False;"

      RunMigrations: "true"

      JwtSettings__Issuer: "PedroIghor"
      JwtSettings__Audience: "https://localhost:5001"
      JwtSettings__SecretKey: "SUA_CHAVE_SECRETA"
      JwtSettings__ExpirationInMinutes: "60"

    depends_on:
      payments-sqlserver:
        condition: service_healthy

  payments-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: payments-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "SuaSenhaForte@123"

    ports:
      - "1434:1433"

    volumes:
      - payments-sqlserver-data:/var/opt/mssql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\" || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  payments-sqlserver-data: